name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: actions/setup-node@v2
    - run: npm i -g @apidevtools/swagger-cli@4

    - name: Bundle spec
      run: "swagger-cli bundle ./rm-oapi.yaml -r -t yaml -o ./deploy/rm-oapi.yaml"
